config/routes.rb
Rails.application.routes.draw do
  get 'users' => 'users#index'
  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  get 'users/:id/edit'=> 'users#edit', as: :user_edit
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'
  get 'users/:id' => 'users#show', as: :user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :phones, dependent: :destroy
  validates :name, presence: true, uniqueness: { scope: :user_id }
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
  validates :number, presence: true, uniqueness: { scope: :contact_id }
  validates :kind, inclusion: %w[home work other]
  validates :main, inclusion: [true, false]
  validates :main, uniqueness: {
    scope: :contact_id,
    message: 'A contact can have only a phone defined as main',
    conditions: -> { where(main: true) }
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts, dependent: :destroy
  has_many :phones, through: :contacts
  validates :name, presence: true, uniqueness: true
  validates :age, numericality: { greater_than_or_equal_to: 0, allow_nil: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(:contacts)
  end

  def show
    @user = User.includes(:contacts, :phones).find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.includes(:contacts, :phones).find_by(id: params[:id])
  end

  def update
    @user = User.includes(:contacts, :phones).find_by(id: params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.includes(:contacts, :phones).find_by(id: params[:id])
    @user.destroy

    redirect_to @user
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :age, :biography)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeminer42TraineeSemana4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div class="div--user div--create-user">
    <%= form.label :username %><br/>
    <%= form.text_field :name, class: "input", required: "required" %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div class="div--error-message"><%= message %></div>
    <% end %>
  </div>

  <div class="div--user div--create-user">
    <%= form.label :age %><br/>
    <%= form.number_field :age, class: "input" %>
    <% user.errors.full_messages_for(:age).each do |message| %>
      <div class="div--error-message"><%= message %></div>
    <% end %>
    
  </div>

  <div class="div--user div--create-user">
    <%= form.label :biography %><br/>
    <%= form.text_area :biography, size: "50x7", class: "input" %>
  </div>

  <div class="div--user div--create-user">
    <%= form.submit  button_name, class: "button button--blue button--blue-create-user"%>
  </div>
<% end %>

<div class="div--button-back">
  <%= link_to 'Back', users_path, class: "button button--blue button--blue-new-user" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= render "form", user: @user, button_name: "Update" %>

app/views/users/index.html.erb
<% if @users %>
  <table class="table">
    <caption><h1>Users</h1></caption>
    <thead>
      <tr>
	<th class="table__th">Username</th>
	<th class="table__th">Contacts</th>
	<th class="table__th">Phones</th>
	<th class="table__th">Actions</th>
      </tr>
    </thead>   
    <tbody>
      <% @users.each do |user| %>
	<tr class="table__tr">
	  <td class="table__td"><%= user.name %></td>
	  <td class="table__td"><%= user.contacts.length %></td>
	  <td class="table__td"><%= user.phones.length %></td>
	  <td class="table__td">
	    <%= link_to 'Show', user_path(user) %>|
	    <%= link_to 'Edit',  user_edit_path(user) %>|
	    <%= link_to 'Delete',  user_path(user), method: :delete, data: { confirm: "Are you sure? "} %>
	  </td>
	</tr>
	<% end %>
    </tbody>
  </table>
  <div class="div div--button">
    <%= link_to 'New', users_new_path, class: "button button--blue button--blue-new-user"%>
  </div>
  
<% else %>
  <h2>Error! Could not retrieve Users from database</h2>
<% end %>

app/views/users/new.html.erb
<%= render "form", user: @user, button_name: "Create" %>

app/views/users/show.html.erb
<h1>User Details</h1>

<% if @user %>
  <div class="div--user">
    <p><b>Username:</b> <%= @user.name %> </p>
    <p> <b>Age:</b><%= @user.age %></p>
    <p><b>Biography:</b><%= @user.biography %></p>
  </div> 
  <div class="div">
    <h2>Contacts</h2>
    <% @user.contacts.each do |contact| %>
      <div class="div div--contacts">
	<p><b>Name:</b> <%= contact.name %> </p>
	<p><b>Birthday:</b> <%= contact.birthday.strftime('%d/%m/%Y') if contact.birthday %> </p>
	<table class="table">
	  <caption><h3>Phones</h3></caption>
	  <thead>
	    <tr>
	      <th class="table__th">Number</th>
	      <th class="table__th">Kind</th>
	      <th class="table__th">Main</th>
	    </tr>
	  </thead>   
	  <tbody>
	    <% contact.phones.each do |phone| %>
	      <tr class="table__tr">
		<td class="table__td"><%= phone.number %></td>
		<td class="table__td"><%= phone.kind %></td>
		<td class="table__td"><%= phone.main %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
      </div>
    <% end %>
  </div>
<% else %>
  <h3>Error!: user not found</h3>
<% end %>

<div class="div--button-back">
  <%= link_to 'Back', users_path, class: "button button--blue button--blue-new-user" %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>